-- seed.sql  —  GENERATED by data/build_kb.py. Do not edit by hand.
-- Lumina Auto standalone chat responder knowledge base.
-- Safe to re-run: truncates KB tables then re-inserts.

begin;
truncate table intent, escalation_rule, funnel_node, reply_sequence, quick_reply, wa_template, business_rule, lead_tag restart identity cascade;

insert into quick_reply (keyword, message) values ('accountnumber', 'We ask for your bank account number because 3 of the 5 major banks we work with require it to process an application.

*You do not have to provide it:* However, leaving it out means we can only submit your application to 2 banks, which greatly lowers your chances of success.

Providing your details allows us to approach all the banks on your behalf to give you the best possible result. 📈');
insert into quick_reply (keyword, message) values ('Nolicencerespond', 'Here are ways to buy a car without a licence, unfortunately a Learner''s Licence won''t work 🚗

🔸When buying cash you don''t need a licence
🔸Nominated driver, Has to be a parent has to live in same household and have same proof of address
🔸If you have a medical disability and then a nominated river (Need a Medical Certificate)
🔸Your Partner Licence and have to be married in Community of Property

Video on this:
https://www.tiktok.com/@zinantalksvw/video/7214415606978710790

What will be the best way for you ?');
insert into quick_reply (keyword, message) values ('Nominated driver check', 'Ok great! but *VERY IMPORTANT*

➡️Is the person your *biological mother / father?*

➡️Or if it is your spouse, *are you married in community of property* and do they have a licence?

➡️Do you and your nominated driver have the same proof of address');
insert into quick_reply (keyword, message) values ('questions morning', 'Good morning! Thanks for reaching out. How can I assist you today?');
insert into quick_reply (keyword, message) values ('nominated driver', 'Here are the things that need to be in place with a nominated driver

➡️Is the person your *biological mother / father?*

➡️Or if it is your spouse, *are you married in community of property* and do they have a licence?

➡️Do you and your nominated driver have the same proof of address');
insert into quick_reply (keyword, message) values ('decline', 'Hey! I received the bank''s response. While we can''t get an approval today, the good news is that we should get it approved in the next 2-3 months! With a little work on your credit score, you''ll be ready in a few short months.

Here is exactly what you need to do (and avoid) to get approved next time:
To-Do List:
🔹 Settle any accounts in arrears.
🔹 Build a new, consistent paying profile over the next 3-6 months. (Keep in mind: cell contracts, Wi-Fi, and memberships don''t count towards building credit). 📱

What to Avoid:
❌ No new personal loans.
❌ No micro loans or payday loans.
❌ Do not apply for vehicle finance anywhere else for now.

Sign up for ClearScore online. It’s 100% free and it will send you a monthly report to show how your score is improving! 📈

I’m definitely keeping your number saved. Please save mine, trust the process, and ask me any questions you might have along the way! 🤝

📌I also offer R5000 for every person you refer to me who buys a vehicle! 💰');
insert into quick_reply (keyword, message) values ('referral', 'Thank you for your interest in our referral program! 🤝

We offer a *R5000* cash reward to YOU for every successful referral you send our way.

*How it works:*
- Visit our website: 🌐 *luminaauto.co.za*
- Click on the *Money Maker* button.
- Submit the contact details of the person looking to buy a vehicle.
- Once your referral successfully purchases and takes delivery of a car from us, we pay you R5000! 💰

There is no limit to how many people you can refer. Let me know if you have someone in mind!');
insert into quick_reply (keyword, message) values ('installments', 'Installments vary from client to client as each person is scored differently by the bank according to their own personal profile.

Installments could be lower or higher but you are looking between R3800pm- R5000pm');
insert into quick_reply (keyword, message) values ('badcredit', 'Here is some general advice that I hope will help you get back on track! :)

Unfortunately, banks cannot approve vehicle finance while your credit profile shows missed payments or accounts in arrears. ⛔

Please Note: Banks need to see a consistent track record of on-time payments before approving a loan. Every missed payment lowers your score, and applying for new credit right now will hurt your profile further.

The good news is that this is completely fixable! Once you bring your accounts up to date, we can start working towards your new vehicle. Here is how you can rebuild:

✅ First step: Catch up on all missed payments and bring your accounts completely up to date.

✅ You will need to maintain a clean, on-time payment record for 3 to 6 months before applying.

✅ A 610 credit score (www.clearscore.co.za) is favorable for vehicle finance, although banks look at other factors too.

✅ Use less than 50% of your available credit. For example, if you have a credit limit of R10k on a store account, only use up to R5k.

✅ Always pay more than the minimum. If your monthly premium is R200, pay R250.

✅ Cellphone, gym, internet contracts, and life policies do not build credibility for vehicle finance.

❌ IMPORTANT: Do not make any new credit applications, as this will drop your score further.

In the meantime, I am saving your number! I always post helpful advice and great vehicle specials on my Status. 🙏

Please save mine to view them, and remember: I offer a R5000 referral fee directly to YOU for each successful referral you send our way! 🤝');
insert into quick_reply (keyword, message) values ('blacklisted', 'Here is some general advice that I hope will help you on your journey! :)

Unfortunately, banks cannot legally approve any new vehicle finance while a profile is actively under debt review. ⛔

Please Note: Nobody can remove debt review from your profile unless all accounts are fully settled. Stay away from scams, and please do not apply for any new credit right now, as it will hurt your profile further.

The good news is that once you complete the process and receive your Clearance Certificate, we can apply for your vehicle! Here is how you can prepare for that day:

✅ Once accounts and arrears are settled, you are basically starting your credit record fresh again.

✅ You will need to build a new paying credit profile from 3 to 6 months.

✅ A 610 credit score (www.clearscore.co.za) is favorable for vehicle finance, although banks look at other factors too.

✅ Use less than 50% of your available credit. For example, if you have a credit limit of R10k on a store account, only use up to R5k.

✅ Always pay more than the minimum. If your monthly premium is R200, pay R250.

✅ Cellphone, gym, internet contracts, and life policies do not build credibility for vehicle finance.

❌ IMPORTANT: Do not make any credit applications, as this may negatively affect you.

In the meantime, I am saving your number! I always post helpful advice and great vehicle specials on my Status. 🙏

Please save mine to view them, and remember: I offer a R5000 referral fee directly to YOU for each successful referral you send our way! 🤝');
insert into quick_reply (keyword, message) values ('6month', 'Do you have 6 months of bank statements that consistently reflects that income?');
insert into quick_reply (keyword, message) values ('docs', 'Thank you for taking my call!😁

The banks need the following documents:

🔅ID
🔅License
🔅Latest 3 payslips
🔅3 month bankstatements

You can email us or Whatsapp me *CLEAR* pictures
( finance@luminaauto.co.za )');
insert into quick_reply (keyword, message) values ('nocredit', 'Because you currently have no active credit facilities (such as a credit card or retail account), banks cannot generate a credit score or assess your repayment history. Consequently, they will not approve vehicle finance at this stage.

Required Next Steps:
1️⃣Open a minor credit facility to establish a profile.
2️⃣Maintain a perfect payment record for 3 to 6 months.
3️⃣Contact us once your credit score is active.

🔴*Note:* Cellphone & network accounts does not affect credit score.

We look forward to assisting you with your vehicle purchase once your credit profile is established.');
insert into quick_reply (keyword, message) values ('debtreview', 'Unfortunately, banks cannot legally approve any new vehicle finance while a profile is actively under debt review. ⛔

*Next Steps*
* You will need to successfully complete your debt review process.
* Once completed, you will be issued a *Clearance Certificate*.
* As soon as you have that certificate, we can apply for vehicle finance!

*Save my number* for when you are ready, or if you need any advice in the future. 🤝

*Remember:* We offer *R5000* referral to *YOU* for every successful referral you send us!

PLEASE NOTE: *NOBODY can remove debt review from your profile unless all accounts has been settled FULLY. And NO official finance/loans can be given to you while under debt review! Stay away from scams and do not continue applying, because it hurts your credit profile even more!!*');
insert into quick_reply (keyword, message) values ('deposit', '*We don''t and never will ask any money upfront*, we are very open and we always work around a deposit to avoid it with the bank 🏦

➡️ BUT if you want you can add a deposit to make your installment less. This can be done anytime during your finance of the car and doesn''t have to be done before buying a car.

Every *R10000* makes your monthly installment less by *R200pm*');
insert into quick_reply (keyword, message) values ('spouse', 'Banks need the following info please:

* Spouse Name and Surname
* Spouse ID number
* Spouse contact number
* Date Married');
insert into quick_reply (keyword, message) values ('winning', 'Hi there! Are you *winning* with the *information?* 🙌🏽 Let me know if you need any assistance.');
insert into quick_reply (keyword, message) values ('arrears', 'Do you have accounts in arrears or are you under debt review?');
insert into quick_reply (keyword, message) values ('whyscore', 'Why is your credit score low?');
insert into quick_reply (keyword, message) values ('catalog', 'We work with all types of vehicles *new, used, and demos!* 🏎️

When it comes to vehicle finance, the banks look at a lot of different factors. They score cars differently, and they also score each person uniquely based on their personal credit profile.

*Here is what makes us different:* We fight for you with the banks! 🥊 We guide you through the whole process and explore every option to see which car gets you the best approval. Once we have that sorted, we present you with a variety of new, used, or demo options to make sure we find the absolute perfect match for you. ✨

You can check out some of our current stock here:
🚗 https://luminaauto.co.za/inventory

But remember, if you don''t see what you want, we can source it for you. Let me know what you have in mind and we can get started! 🤝');
insert into quick_reply (keyword, message) values ('future', 'I’ve got your number saved! ✅ Save mine as well so we stay in touch. Don''t stress at all, we will get you into a car, *let’s just check back in 2-3 months. ⏳🚙*

For now, please avoid putting in any more applications anywhere else. Just trust the process! When you check in with us later, *we will just refresh your profile to see the new updates.* We are fully committed to helping you! 🥳🙌');
insert into quick_reply (keyword, message) values ('low income', 'To qualify for vehicle finance, you do need *a minimum net take-home pay of R8500 p/m, or R20000 if you are self-employed.* I know you''ll reach those goals soon, and I''ll be right here ready to help you get your dream car when you do! 🚘✨

📢📢 I''m saving your details on my side. Definitely If you know anyone looking for a car, *I offer a R1000 - R10,000 spotter’s fee for every successful referral!* 💸🔥');
insert into quick_reply (keyword, message) values ('no licence', 'That is 100% okay! *Focus on getting that license, and I will be waiting to hand over the keys to your new car when you''re ready!* 🥳🔑

I''ve got your number saved for when the time comes. Feel free to message me anytime if you have any questions! 📱

Make sure to save my number as well to see my newest stock and specials on my WhatsApp statuses. 🤩

‼️ Also, don''t forget! I give a R1000 - R5000 cash bonus for every person you refer who purchases a vehicle from me! 💰🔥');
insert into quick_reply (keyword, message) values ('Based', 'We are based in Pretoria and *we deliver nationwide free of charge!* 🌎

Where ever you are we are 🚗');
insert into quick_reply (keyword, message) values ('options', 'We work on new, used and demo 🏎. When we do vehicle finance there is a lot of factors to take in mind with the bank and how they score cars, they also score each person differently based on their personal profile.

What makes us different is we fight with the bank, we help and guide our clients and work through all the different options to see which car they qualify for the best with the bank. After that, we present all the different options for you based on new, used and demos and make sure we get the perfect one for you');
insert into quick_reply (keyword, message) values ('creditscore', 'When purchasing a car via finance it is not so much about the credit score but more based on your personal profile ✅

Stuff that also boosts chances of approval is stuff like your education history, workplace, work position, current time at employer age, etc. Banks are also eager to help first-time car buyers and if they have had a car in the past.

Another example is if you are behind on any payments, what is your credit history, how long have you been paying credit, how much percentage of your credit do you use, etc

So as you can see your credit score doesn''t really have such an impact on your car finance, that is where we go the extra mile and build you a strong profile, all of our clients have a fair chance of approval!

With us, you don''t just apply we also walk the road with you to make sure you do get approved! That is what makes us the best in the industry ❤');
insert into quick_reply (keyword, message) values ('trade in', 'How a trade in works

- we need to see what your settlement amount is (what you owe the bank now) vs what your car is worth

- if your settlement is higher than the car is worth you will have a shortfall, the shortfall you either need to settle it cash or we need if possible to load ontop of the new deal. Every R10k we load will make the instalment go up by R200

- if your car is worth more than your settlement you can either take the extra capital as a refund or you can put it down as a deposit on the new deal

•••••••••••••••••••••••••••••

Please send me the below details of your trade in

🚗 amount you owe
🏦 with who did you finace
🏎 make
🏎 model
🏎 year
🏎 engine (1.4 etc)
🏎 transmission (man or auto)
🏎 kms
Any extras we should know of like sunroof etc');
insert into quick_reply (keyword, message) values ('preapprove1', 'Hi👋

I am following-up regarding your vehicle application.

We are ready to move forward to the next steps, but we just need your supporting documents to finalize the bank''s validation process. 📄

Please let me know if you need any assistance gathering them, or when we can expect to receive them.');
insert into quick_reply (keyword, message) values ('preapprove2', 'Hi👋

I have been trying to reach you via WhatsApp and phone calls to finalize your vehicle application, but I haven''t been able to get through. 📱

The bank requires your supporting documents to keep your file active and proceed with the validation.

Is there an alternative number where I can reach you, or a better time to call? Please let me know how you would like to proceed so we can avoid any delays on your profile. ⏳');
insert into quick_reply (keyword, message) values ('preapprove3', 'Hi ! I trust you are doing well

I have been trying to get hold of you on whatsapp and through calls but haven''t been getting through to you?

Is there something we did wrong or you would like us to approve? What do you want me to do for you to take the next steps 🫶🏽

*I don''t want your credit profile to be affected in a negative way because of the pending application which is reflecting on your name which can result in a negative way on any future enquires even blocking you ❌*

Please respond to this message for us to assist you and also to help us prevent any negative affect to your profile 🫶');
insert into quick_reply (keyword, message) values ('preapprove4', 'VERY IMPORTANT UPDATED REGARDING YOUR CREDIT PROFILE
Hey {{1}} 🙋🏾‍♂️ the status of your profile is getting very serous and stands a risk ‼️

⚠️ I have been trying to get hold of you on WhatsApp and through calls but haven''t been getting through to you and we must update the bank on the status of your profile to prevent it from being handed over

Is there something we did wrong or you would like us to approve? Rather discuss with me, then I can assist not responding is only making it worse

I don''t want your credit profile to be affected in a negative way because of the pending application which is reflecting on your name which can result in a negative way on any future enquires even blocking you ❌');
insert into quick_reply (keyword, message) values ('badcredit1', 'Hi👋

I am following-up regarding your vehicle application.

We are ready to move forward to the next steps, but we just need your supporting documents to finalize the bank''s validation process. 📄

Please let me know if you need any assistance gathering them, or when we can expect to receive them.');
insert into quick_reply (keyword, message) values ('badcredit2', 'Hi👋

I have been trying to reach you via WhatsApp and phone calls to finalize your vehicle application, but I haven''t been able to get through. 📱

The bank requires your supporting documents to keep your file active and proceed with the validation.

Is there an alternative number where I can reach you, or a better time to call? Please let me know how you would like to proceed so we can avoid any delays on your profile. ⏳');

insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30732, 'tiktok_intro', 'opener', 'Hey {{name}}! 😁

I''m *Albert from Lumina Auto* 🏎️

*I saw you just filled out a form on TikTok and I wanted to reach out personally to assist you* 🕺

Whether you’re looking for a *brand-new ride or a quality demo/used car,* I’m here to handle the heavy lifting, especially when it comes to securing the best financing for you! 💳

You can just respond to this message then we can check exactly what we can get for you 🚗', '["Let''s get the ball rolling!"]'::jsonb, 636);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30743, 'excited_qualify_5min', 'opener', 'Hey {{name}}! 🤩🚗

I am very excited to get you the deal of a lifetime on your new dream car! 🎉

*Would you like to see how you qualify, it only takes 5minutes*. ✅

*NO DOCUMENTS NEEDED*', '["Let''s make it happen!", "Not interested"]'::jsonb, 580);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30748, 'no_reply_reminder', 'reminder', 'Hey {{name}} I see you haven''t gotten back to me 💔 I offer the best deals in SA and go out of my way for my customers! 🇿🇦

I strive to bring excellent service to my clients 🎉

With that being said please keep in mind we are on of the biggest motor groups in South-Africa! *Which mean we sell all brands 🚗
Anything from VW, Suzuki, Renault, Hyundai, BMW, Ford and the list goes on* 💥

Is there anything unclear or uncertain in which I communicated with you ?', '["Sorry I just got busy", "Give me the best deal eva!!", "I won''t qualify for car finance", "Not interested"]'::jsonb, 462);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30733, 'sorry_couldnt_assist_referral', 'closer', 'Sorry I couldn''t assist to make your dream come true 💔

Im saving your number, save mine to see updates on specials, tips and the latest releases on my status

*I offer R5000 per Client that you refer to me that successfully buys a vehicle* 💰💰💰

Imagine giving me 2-4 clients a month 😊', '[]'::jsonb, 290);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30749, 'application_submitted', 'status', 'Hi {{name}}! This whatsapp is to confirm that your application has been submitted to the banks.
We are currently awaiting their response and will provide you with an update as soon as it becomes available.

You can also send the following to speed up the process🏁

🔅ID
🔅License
🔅3 Months Bankstatements
🔅Latest Payslip

*If already sent, please ignore*', '[]'::jsonb, 134);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30746, 'declined_advice', 'status', 'Hey {{name}}! I received the bank''s response. While we can''t get an approval today, the good news is that we should get it approved in the next 2-3 months! With a little work on your credit score, you''ll be ready in a few short months.

Here is exactly what you need to do (and avoid) to get approved next time:
To-Do List:
🔹 Settle any accounts in arrears.
🔹 Build a new, consistent paying profile over the next 3-6 months. (Keep in mind: cell contracts, Wi-Fi, and memberships don''t count towards building credit). 📱

What to Avoid:
❌ No new personal loans.
❌ No micro loans or payday loans.
❌ Do not apply for vehicle finance anywhere else for now.

Sign up for ClearScore online. It’s 100% free and it will send you a monthly report to show how your score is improving! 📈

I’m definitely keeping your number saved. Please save mine, trust the process, and ask me any questions you might have along the way! 🤝

📌I also offer R5000 for every person you refer to me who buys a vehicle! 💰', '[]'::jsonb, 45);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30745, 'press_hi_button', 'reengage', 'Hey {{name}}! Please respond or press the "Hi" button to this message to allow me to send you further information 👇', '[]'::jsonb, 10);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30883, 'finance_preapproved', 'status', '🔴FINANCE UPDATE: PRE-APPROVED🔴

👤 Client Details:

{{name}}

{{phone}}

Contact to finalize!', '[]'::jsonb, 8);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30738, 'debt_review_advice_tmpl', 'advice', 'Unfortunately, banks cannot legally approve new vehicle finance while under debt review. ⛔

Nobody can remove debt review unless all accounts are fully settled. Avoid scams, and do not apply for new credit, as it damages your profile.

Once you receive your Clearance Certificate, we can apply! How to prepare:
✅ Settle accounts to start your credit fresh.
✅ Build a paying credit profile for 3 to 6 months.
✅ Aim for a 610 credit score (ClearScore).
✅ Keep credit utilization under 50% (e.g., R5k on a R10k limit).
✅ Always pay more than the minimum installment.
✅ Cellphone and gym contracts do not build vehicle credibility.
❌ IMPORTANT: Do not make any credit applications.

I am saving your number to share helpful advice and vehicle specials on my Status. 🙏

Please save mine. Remember: Lumina Auto offers a R5000 referral fee directly to YOU for each successful referral! 🤝', '[]'::jsonb, 7);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (31765, 'looking_to_finance', 'opener', 'Hey Are you looking to finance a car?, Albert from Lumina Auto 💪', '[]'::jsonb, 14);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (31766, 'good_morning_assist', 'opener', 'Good morning! Thanks for reaching out. How can I assist you today?', '[]'::jsonb, 3);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (31211, 'based_delivery', 'info', 'We are based in Pretoria and *we deliver nationwide free of charge!* 🌎

Wherever you are, we are 🚗', '[]'::jsonb, 1);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (31199, 'system_offline', 'ops', 'Hi {{name}}! 👋

Albert here from Lumina Auto.

I am reaching out with a quick update regarding your vehicle finance application. Our system connection to the banking portals is currently offline🏦, meaning we are temporarily unable to submit new applications or receive feedback on pending ones.❌

The system will be fully back online next week Wednesday.🗓️

If you are happy to wait, we will prioritize your application the moment connectivity is restored. However, if you prefer to look at alternative options in the meantime, please let me know.📲

Thank you for your patience and understanding.

Regards,
Albert
Lumina Auto', '[]'::jsonb, 1);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (31320, 'system_back_online', 'ops', 'Hey {{name}}! 👋

Albert here from Lumina Auto.

*Good news!* Our system link to the banks should officially be *back online* today! 🏦✨

Before we push forward, I just wanted to check if you’ve already applied anywhere else while we were offline, or if *you''d like us to go ahead and submit your application here?* Alternatively, let me know if you''d prefer to cancel it for now. 📲

Looking forward to your update so we can *get things moving for you.*

Best regards,
Albert

*Lumina Auto*', '["Let''s Submit!", "Applied Elsewhere", "Cancel"]'::jsonb, 1);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30789, 'pausing_file', 'closer', 'Hey {{name}}! Albert here from Lumina Auto! 👋

I am currently updating my records and will be pausing your vehicle file for now. We understand that plans change and timing isn''t always perfect, that is completely okay! Sorry I couldn''t make your dream come true now, but we will be doing it in the near future 🎉

Whenever you are ready to get your dream vehicle, simply reach out and we will pick up right where we left off we sell all brands, new used and demo 🚘

❗ A quick tip: Keep your credit profile healthy by avoiding any unnecessary credit applications in the meantime. 📈

Remember: We offer a R5000 referral to YOU for every successful referral you send us! 🤑', '[]'::jsonb, 1);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30832, 'referral_intro', 'opener', 'Hi {{name}}! 👋

I’m Albert from Lumina Auto.

I was recently given your details by a mutual contact who mentioned you might be looking for a new vehicle. I help my clients source, finance, and deliver quality cars that perfectly match their needs and budget. 🚗

I would love to see if I can assist you in finding your next car.', '[]'::jsonb, 1);
insert into wa_template (template_id, name, category, body, buttons, usage_count) values (30735, 'finance_preapproved_2', 'status', 'FINANCE UPDATE: PRE-APPROVED

👤 Client Details:

{{name}}

{{phone}}

Contact to finalize!', '[]'::jsonb, 2);

insert into funnel_node (code, question, options) values ('start', 'How can I assist you today 😊

You can select any of the options below 👇', '[{"title": "I want my dream car now!", "next": "licence"}, {"title": "Check If I Qualify", "next": "licence"}, {"title": "I''ve Got Questions", "next": "qr:questions morning"}]'::jsonb);
insert into funnel_node (code, question, options) values ('licence', 'Great! Here are 3 quick Questions so we can see how you qaulify 🏎

Do you have a drivers Licence ?', '[{"title": "Yes I Do", "next": "credit", "set": {"licence": "yes"}}, {"title": "No Licence Yet", "next": "qr:no licence", "set": {"licence": "no"}}, {"title": "I Only Have Learners", "next": "learners_reply", "set": {"licence": "learners"}}]'::jsonb);
insert into funnel_node (code, question, options) values ('credit', 'Thanks {{name}}! Things are looking good!

We fight for every client, no matter your credit profile. We’ll help you understand the process and what’s needed and make your dream a reality! 🏎✅

How''s your credit profile looking?', '[{"title": "Good Credit Record", "next": "timeline", "set": {"credit": "good"}}, {"title": "Its looking better", "next": "timeline", "set": {"credit": "improving"}}, {"title": "Im not sure", "next": "qr:arrears", "set": {"credit": "unsure"}}, {"title": "Blacklisted/Debt Review", "next": "qr:debtreview", "set": {"credit": "debt_review"}}, {"title": "Missed Many Payments", "next": "missed_payments", "set": {"credit": "missed"}}, {"title": "No Credit Record", "next": "qr:nocredit", "set": {"credit": "none"}}]'::jsonb);
insert into funnel_node (code, question, options) values ('timeline', 'To get you the best deal ever we just need to answer a few quick questions 🤝

🟢 If you are happy and all is good WHEN are you looking to buy then?', '[{"title": "As Soon As Possible", "next": "income", "set": {"timeline": "asap"}}, {"title": "Within A Month", "next": "income", "set": {"timeline": "month"}}, {"title": "Need to sort stuff", "next": "need_sort", "set": {"timeline": "later"}}]'::jsonb);
insert into funnel_node (code, question, options) values ('income', 'Let''s GOOO! 🔥

Are you permanently employed and earn a net salary on your payslip of R8500 or more per month?

(Self Employed must earn a minimum per month)', '[{"title": "Yes sir!", "next": "qr:docs", "set": {"income": "yes"}}, {"title": "Not yet", "next": "qr:low income", "set": {"income": "no"}}, {"title": "It''s Complicated", "next": "ESCALATE", "set": {"income": "complicated"}}]'::jsonb);
insert into funnel_node (code, question, options) values ('missed_payments', 'Thats not bad news at all! As long as you are not behind on any payments or missed payments we will be able to assist!

Thats what makes us different! We fight for each one of our clients!

Which of the options fits you best??', '[{"title": "Let''s do it!", "next": "timeline"}, {"title": "Let me explain first", "next": "ESCALATE"}, {"title": "3+ Missed Payemnts", "next": "qr:badcredit"}]'::jsonb);
insert into funnel_node (code, question, options) values ('learners_reply', 'Thanks {{name}} Here are ways to buy a car, unfortunately a Learner''s Licence won''t work 🚗', '[{"title": "Nominated Driver", "next": "nominated_driver"}, {"title": "Medical Reason", "next": "ESCALATE"}, {"title": "Will Get Licence", "next": "qr:no licence"}]'::jsonb);
insert into funnel_node (code, question, options) values ('nominated_driver', 'Ok great! but *VERY IMPORTANT*

➡️Is the person your biological parent, or your spouse (married in community of property) with a licence, and do you share the same proof of address?', '[{"title": "Yes - My Parents", "next": "credit"}, {"title": "Yes - My Partner", "next": "credit"}, {"title": "None of these", "next": "qr:Nolicencerespond"}]'::jsonb);
insert into funnel_node (code, question, options) values ('need_sort', '{{name}}, we provide solutions for each person needs. Your 1st instalment will not be now. Car prices only go up never down.', '[{"title": "Im happy with that!", "next": "income"}, {"title": "Does not help me", "next": "ESCALATE"}, {"title": "Let me explain first", "next": "ESCALATE"}]'::jsonb);

insert into reply_sequence (name, steps, note) values ('credit_diagnostic', '["whyscore", "arrears"]'::jsonb, 'Mirrors the human takeover: ask ''Why is your credit score low?'' then ''/arrears'' before giving advice. Once the client answers (arrears/missed -> badcredit; debt review/blacklisted -> debtreview; no credit -> nocredit), the next turn sends the right advice.');

insert into intent (name, priority, action, target, patterns, note) values ('location', 20, 'qr', 'Based', '["where.{0,15}(you|u|your office|guys).{0,15}(base|located|situated|office)", "\\bwhere are (you|u|your)\\b", "\\bwhere.{0,10}(based|located)\\b", "\\blocation\\b", "which (city|town|area)", "branch in", "do you deliver", "nationwide", "\\bdelivery\\b", "come to (you|your office)"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('deposit_or_upfront', 25, 'qr', 'deposit', '["\\bdeposit\\b", "up\\s?front", "money (first|before)", "pay.{0,10}before", "(afraid|scared|worried|nervous).{0,15}scam", "scam.{0,15}(afraid|scared|money)", "money you need to qualify", "afraid.*money", "\\bballoon\\b"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('installments_price', 30, 'qr', 'installments', '["install?ments?", "how much.{0,20}(pay|month|car|cost|instal|deal|finance)", "\\bprice\\b", "repayment", "per month", "monthly (install?ment|payment|repay|premium|instal|amount)", "instal?ment.{0,10}(not more|less than|under|around|about)", "what.{0,15}instal"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('documents', 35, 'qr', 'docs', '["\\bdocuments?\\b", "what.{0,15}(need|require).{0,15}(qualify|apply|buy|vehicle|car)", "requirements?", "\\bpapers?\\b", "what do i need", "what is needed", "what.{0,10}(bye|buy).{0,10}(a )?(car|vehicle)"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('catalog_stock', 40, 'qr', 'catalog', '["which cars?", "what cars?", "\\bstock\\b", "inventory", "list (of|off) cars?", "show me.{0,15}cars?", "cars? (do you|available)", "varieties", "7\\s?seater", "panel van", "\\bbakkies?\\b", "automatic cars?", "do you (have|sell|stock|do).{0,25}(car|bakkie|van|suv|sedan|hatch|automatic|manual|vw|toyota|ford|renault|hyundai|suzuki|bmw|polo|triber|ecosport|golf|tigo|cherry|rav4)", "(triber|ecosport|polo|golf|tigo|rav4|cherry).{0,10}(available|in stock)", "which (cars?|vehicles?).{0,10}(qualify|get)", "\\bused car\\b", "i like (this|that) car", "interested in (this|the|a) (car|vehicle)", "what (are you|do you) (offer|have)", "give me more info", "more info on this"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('credit_score_info', 45, 'qr', 'creditscore', '["how much credit score", "what.{0,15}credit score.{0,15}(need|looking|require)", "minimum credit score", "what.{0,10}score.{0,10}(need|require|looking)"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('debt_review', 50, 'qr', 'debtreview', '["debt\\s*review", "under review", "debt counsel"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('blacklisted', 55, 'qr', 'blacklisted', '["black\\s?list", "\\bitc\\b", "judg? e?ment", "handed over", "\\bred flag\\b"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('bad_credit_arrears', 60, 'qr', 'badcredit', '["arrears", "missed.{0,10}payment", "behind.{0,12}(payment|on|with)", "bad credit", "(low|bad|poor|not good|not that good|not great|bit damage|damaged|messed).{0,12}credit", "credit.{0,14}(is )?(bad|low|poor|not good|isn.?t good|not that good|not great|damage|messed|ruined|bit damage|not so)", "defaulted?", "(score|credit).{0,12}(is )?[3-6]\\d\\d\\b", "[3-6]\\d\\d\\b.{0,12}(score|credit)"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('no_credit', 65, 'qr', 'nocredit', '["no credit (record|history|profile|score)", "never (had|took|used).{0,10}credit", "don''?t have (any )?credit", "no active credit"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('nominated_driver', 71, 'qr', 'nominated driver', '["nominated driver", "nominee", "someone else.{0,12}(licen|drive)", "my (mother|father|parent|mom|dad|husband|wife|partner|spouse|brother|sister|son|daughter|cousin|uncle|aunt|in.?law|family).{0,20}(licen|drive)"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('no_licence', 72, 'qr', 'no licence', '["(\\bno\\b|don''?t have|do not have|without|haven''?t got|no valid|dont have).{0,15}(licen|license)", "(licen|license).{0,12}(no|not yet|expired|dont|don''?t have)", "don''?t.{0,6}(have a )?licen"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('licence_question', 73, 'qr', 'Nolicencerespond', '["(must|need|require|necessary|have to|is it a must|do i need).{0,20}(licen|license)", "(licen|license).{0,15}(must|required|necessary|need)"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('learners_only', 74, 'qr', 'Nolicencerespond', '["learner''?s?( licence| license| licens)?", "only.{0,10}learner", "busy.{0,10}(with )?(my )?learner"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('spouse_info', 76, 'qr', 'spouse', '["married in com", "community of property", "\\bspouse\\b", "my (husband|wife).{0,12}licen"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('low_income', 78, 'qr', 'low income', '["earn.{0,10}[rR]?\\s?[1-7][ ,.]?\\d{3}\\b", "salary.{0,12}(of )?[rR]?\\s?[1-7][ ,.]?\\d{3}\\b", "[1-7][ ,.]?\\d{3}\\b.{0,15}(salary|earn|month|pm|net|take.?home|per month)", "salary.{0,10}(is )?(low|too low|small)", "don''?t (earn|make) enough", "below.{0,10}(8500|8 500)", "less than.{0,10}8500", "(monthly )?salary of [1-7]"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('referral', 80, 'qr', 'referral', '["refer(r?al)?", "money maker", "spotter", "commission.{0,10}refer", "how does the refer"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('trade_in', 82, 'qr', 'trade in', '["trade.?in", "trade my", "settlement", "my (current )?car.{0,15}(swap|trade|exchange)", "exchange my car"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('self_employed', 84, 'qr', '6month', '["self.?employ", "own business", "no payslip", "don''?t have.{0,10}payslip", "i''?m a business", "business owner", "we don''?t get payslip"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('account_number', 86, 'qr', 'accountnumber', '["why.{0,15}(bank )?account number", "account number.{0,12}(why|need|safe|for)"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('interested_finance', 90, 'funnel', 'start', '["(want|need|looking for|interested|get).{0,15}(car|vehicle|bakkie|finance)", "do you (do|offer|have).{0,10}finance", "finance a (car|vehicle)", "i (want|need) a car", "check if i qualify", "am i qualif", "do i qualif", "can i (get|qualify).{0,10}(a )?(car|finance)", "want to check if i", "i want car", "i just need a car", "bu[sy]{2,3} a car", "wanna (buy|busy|get) a car", "looking for a car"]'::jsonb, NULL);
insert into intent (name, priority, action, target, patterns, note) values ('greeting', 100, 'qr', 'questions morning', '["^\\s*(hi|hey|hello|good\\s*(morning|afternoon|evening)|molo|sawubona|dumela|goeie|hallo|greetings)\\b"]'::jsonb, 'Evaluated last: any specific intent outranks a plain greeting.');

insert into escalation_rule (name, reason, patterns, hard) values ('rent_to_own', 'No standard policy captured for rent-to-own; answered case-by-case.', '["rent.?to.?own", "rent to buy"]'::jsonb, false);
insert into escalation_rule (name, reason, patterns, hard) values ('application_status', 'Live bank feedback required - must be checked by a human/agent.', '["(feedback|update|news|response|word).{0,15}(bank|application|app|finance)", "status of my (app|application)", "did (you|it) (submit|go through)", "has.{0,10}been (approved|submitted)", "\\bany (feedback|news|update|word)\\b", "submitted.{0,15}application"]'::jsonb, false);
insert into escalation_rule (name, reason, patterns, hard) values ('specific_vehicle_availability', 'Live stock/price check needed for a specific listed vehicle.', '["still available", "is the .{0,30}(available|in stock)", "price of the \\w+", "\\br ?\\d{4,}\\b.{0,20}(available|this car|that car|the car)", "interested in (the|this) \\d{4}"]'::jsonb, false);
insert into escalation_rule (name, reason, patterns, hard) values ('talk_to_human', 'Explicit request for a person / phone call.', '["(talk|speak|chat).{0,15}(human|person|someone|agent|consultant|manager|you guys)", "can i (call|phone)", "call me", "phone me", "\\byour number\\b", "come in contact", "get in touch", "how (can|do) i (reach|contact)", "contact you"]'::jsonb, false);
insert into escalation_rule (name, reason, patterns, hard) values ('legal_or_complaint', 'Legal threat / complaint - must be handled by a human.', '["lawyer", "legal action", "ombud", "popia", "report you", "take you to", "consumer (council|protection)", "\\brefund\\b"]'::jsonb, true);
insert into escalation_rule (name, reason, patterns, hard) values ('abuse', 'Abusive/hostile - de-escalate with a human.', '["\\b(fuck|thief|thieves|fraudster|liar|useless|idiot|nonsense|bullshit)\\b", "you.{0,15}(are|guys are|re).{0,10}scam", "this is.{0,10}scam", "\\bscammers\\b", "\\bfrauds?\\b"]'::jsonb, true);

insert into business_rule (key, value) values ('min_income_employed_net_pm', '8500'::jsonb);
insert into business_rule (key, value) values ('min_income_self_employed_pm', '20000'::jsonb);
insert into business_rule (key, value) values ('licence_required', 'true'::jsonb);
insert into business_rule (key, value) values ('learners_accepted', 'false'::jsonb);
insert into business_rule (key, value) values ('nominated_driver_allowed', 'true'::jsonb);
insert into business_rule (key, value) values ('deposit_required', 'false'::jsonb);
insert into business_rule (key, value) values ('deposit_effect_per_10000_rands', '200'::jsonb);
insert into business_rule (key, value) values ('based_in', '"Pretoria"'::jsonb);
insert into business_rule (key, value) values ('delivery', '"Nationwide, free of charge"'::jsonb);
insert into business_rule (key, value) values ('referral_fee_rands', '5000'::jsonb);
insert into business_rule (key, value) values ('docs_required', '["ID", "Driver''s License", "Latest 3 payslips", "3 months bank statements"]'::jsonb);
insert into business_rule (key, value) values ('installment_range_pm', '"R3800 - R5000"'::jsonb);
insert into business_rule (key, value) values ('clearscore_target', '610'::jsonb);
insert into business_rule (key, value) values ('banks_total', '5'::jsonb);
insert into business_rule (key, value) values ('banks_requiring_account_number', '3'::jsonb);
insert into business_rule (key, value) values ('email', '"finance@luminaauto.co.za"'::jsonb);
insert into business_rule (key, value) values ('website', '"luminaauto.co.za"'::jsonb);
insert into business_rule (key, value) values ('inventory_url', '"https://luminaauto.co.za/inventory"'::jsonb);
insert into business_rule (key, value) values ('referral_button', '"Money Maker"'::jsonb);
insert into business_rule (key, value) values ('office_days', '"Weekdays only"'::jsonb);
insert into business_rule (key, value) values ('feedback_timing', '"Apps submitted same day; bank feedback typically next afternoon"'::jsonb);
insert into business_rule (key, value) values ('vehicle_types', '["new", "used", "demo"]'::jsonb);
insert into business_rule (key, value) values ('brands', '"All brands (VW, Suzuki, Renault, Hyundai, BMW, Ford, etc.)"'::jsonb);
insert into business_rule (key, value) values ('agent_persona', '"Albert from Lumina Auto"'::jsonb);
insert into business_rule (key, value) values ('hands_off_tags', '["Approved - Need Docs", "Validations Pending", "Vals Done"]'::jsonb);

insert into lead_tag (name, meaning, sample_count) values ('New Lead', 'Fresh lead, not yet qualified', 579);
insert into lead_tag (name, meaning, sample_count) values ('TikTok Ads Lead', 'Came from a TikTok lead form', 240);
insert into lead_tag (name, meaning, sample_count) values ('Blacklisted', 'Under debt review / blacklisted / ITC', 184);
insert into lead_tag (name, meaning, sample_count) values ('Bad Credit', 'Missed payments / arrears / low score', 136);
insert into lead_tag (name, meaning, sample_count) values ('No Licence', 'No valid driver''s licence', 85);
insert into lead_tag (name, meaning, sample_count) values ('App Submitted', 'Application submitted to banks', 76);
insert into lead_tag (name, meaning, sample_count) values ('Application Received', 'Docs/application received from client', 63);
insert into lead_tag (name, meaning, sample_count) values ('Application Declined', 'Bank declined', 47);
insert into lead_tag (name, meaning, sample_count) values ('Low Income', 'Below income threshold', 11);
insert into lead_tag (name, meaning, sample_count) values ('Approved - Need Docs', 'Approved, awaiting documents', 1);
insert into lead_tag (name, meaning, sample_count) values ('Validations Pending', 'Bank validations pending', 2);

commit;