-- Add advanced deal structure columns
ALTER TABLE deal_records 
ADD COLUMN IF NOT EXISTS discount_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS dealer_deposit_contribution NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS external_admin_fee NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS bank_initiation_fee NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_financed_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS client_deposit NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gross_profit NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS recon_cost NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cost_price NUMERIC DEFAULT 0;